databases:
  - name: mumbai-realestate-db
    databaseName: mumbai_realestate
    plan: basic-256mb

services:
  - type: web
    name: mumbai-realestate
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mumbai-realestate-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.0"
